import PageHero from '../components/layout/PageHero'
import { LICENSE as L } from '../data/license'

// The licence page behind the Modrinth and CurseForge licence-URL fields. A store page can be
// edited, moved or deleted; a link in a store's licence field is expected to answer forever, so
// this page is the durable statement and the stores point at it.
//
// It holds NO licence prose of its own. Every sentence and every number comes from
// src/data/license.ts, which is GENERATED by tools/legal.py in the forevercraft-datapack repo
// from the packs that actually ship — the same source that writes LICENSE.txt into each zip.
// Correcting a figure here by hand would put the page and the download back out of step, which
// is the failure this whole arrangement exists to prevent.

const HEADING = "font-['Pixelify_Sans'] text-[0.7rem] text-yellow-400 tracking-widest mt-10 mb-3"

function Sentence({ children }: { children: string }) {
  return <>{children.charAt(0).toUpperCase() + children.slice(1)}</>
}

export default function License() {
  const b = L.bedrock
  return (
    <div className="bg-stone-950 text-stone-200 min-h-screen">
      <PageHero
        title="LICENSE"
        badge="LEGAL"
        subtitle="What you may do with these packs, and what isn't ours to give."
        particleColor="rgba(150, 150, 150, 0.2)"
      />

      <div className="max-w-[900px] mx-auto px-8 py-16">
        <div className="font-['Crimson_Pro'] text-lg text-stone-300 leading-relaxed space-y-6">
          <p className="text-stone-500 text-base">
            Covers every pack published by {L.holder}, across both editions of Minecraft.
          </p>

          <h2 className={HEADING}>THE PACKS</h2>
          <ul className="list-disc list-inside space-y-2 text-stone-400">
            {L.packs.map((p) => (
              <li key={`${p.title}-${p.kind}`}>
                <span className="text-stone-200">{p.title}</span>{' '}
                <span className="text-stone-500">— {p.kind}</span>
              </li>
            ))}
          </ul>
          <p>
            All of them are <span className="text-stone-100">&copy; {L.holder}</span>, all rights
            reserved, and all of them are free. The code, models, geometry, item icons and original
            artwork are ours; the sections below say plainly which parts are not.
          </p>

          <h2 className={HEADING}>WHAT YOU MAY DO</h2>
          <ul className="list-disc list-inside space-y-2 text-stone-400">
            {L.allows.map((a) => (
              <li key={a}><Sentence>{a}</Sentence></li>
            ))}
          </ul>

          <h2 className={HEADING}>WHAT YOU MAY NOT DO</h2>
          <ul className="list-disc list-inside space-y-2 text-stone-400">
            {L.forbids.map((f) => (
              <li key={f}><Sentence>{f}</Sentence></li>
            ))}
          </ul>
          <p>{L.askFirst}</p>

          <h2 className={HEADING}>MOJANG&apos;S MATERIAL — THE JAVA DATAPACKS</h2>
          <p>
            The Java packs contain no textures, models, sounds or other artwork from Minecraft. They
            do contain files in the <code className="text-stone-400">minecraft</code> namespace — loot
            tables, recipes and tags that replace vanilla ones so the packs&apos; content can appear in
            ordinary gameplay:
          </p>
          <ul className="list-disc list-inside space-y-2 text-stone-400">
            {L.packs.filter((p) => p.vanillaFiles !== null).map((p) => (
              <li key={`${p.title}-${p.kind}`}>
                <span className="text-stone-200">{p.title}</span> — {p.vanillaFiles} files
              </li>
            ))}
          </ul>
          <p>
            Those are derived from Minecraft&apos;s own data files, &copy; Mojang AB, and remain
            subject to the Minecraft End User License Agreement. They are not licensed by us.
          </p>

          <h2 className={HEADING}>MOJANG&apos;S MATERIAL — THE BEDROCK ADD-ON</h2>
          <p>
            {L.furniture} on Bedrock is a different case, and a much larger one. Of the{' '}
            {b.total}{' '}
            texture files its resource pack ships,{' '}
            <span className="text-stone-100">{b.mojang} are Minecraft
            textures</span>, &copy; Mojang AB — {b.fromBedrock} from Mojang&apos;s own Bedrock sample
            repository and {b.fromJava} from Minecraft: Java Edition. {b.unmodified} are unmodified,
            some cropped to a single frame of a vanilla animation; {b.changed} are recoloured or
            sliced into animation frames.
          </p>
          <p>
            They are there so that furniture matches the vanilla blocks it is built from — a chair
            made of birch planks has to be birch. A further {b.icons} item icons are renders of our
            own geometry wearing that same vanilla art, so they contain Mojang&apos;s pixels too.
          </p>
          <p>
            None of it is licensed by us. It remains the property of Mojang AB under the{' '}
            <a
              href={L.eula}
              className="text-yellow-400/90 hover:text-yellow-300 underline underline-offset-4"
              target="_blank"
              rel="noreferrer noopener"
            >
              Minecraft End User License Agreement
            </a>
            , and no rights in it are granted to you.
          </p>

          <h2 className={HEADING}>WHY NOT AN OPEN LICENSE</h2>
          <p>
            People ask, so: MIT, Apache, GPL and the Creative Commons licences all grant the
            recipient rights in <em>everything</em> the project contains. We cannot grant anyone
            rights in Mojang&apos;s textures, so choosing one of them would be claiming to give away
            something that was never ours. All rights reserved is the honest answer, and it is why
            these packs are free rather than open.
          </p>

          <h2 className={HEADING}>DISCLAIMER</h2>
          <p className="text-stone-400">{L.disclaimer}</p>
        </div>
      </div>
    </div>
  )
}
