// GENERATED by tools/gen_site_furniture.py in the forevercraft-datapack repo.
// Do not edit. The control list is parsed from LISTING-DESCRIPTION.md (itself
// derived from the shipped main.js) and the piece count is read from the add-on,
// so the website cannot advertise a button the pack does not have.
// Last generated from: Forevercraft-Furnishings-1.0.29.mcaddon

export const FURNITURE = {
  "name": "All The Furniture",
  "pieces": 248,
  "editions": [
    "Minecraft: Java Edition (data pack)",
    "Minecraft: Bedrock Edition (add-on)"
  ],
  "catalogue": {
    "recipe": "one Book + one Any Log",
    "name": "Furnishing Catalogue"
  },
  "rule": {
    "use": "Right-click — use it. Sit on a chair, open a cabinet.",
    "manage": "Sneak + right-click — open the Manage menu."
  },
  "groups": [
    {
      "title": "Placing & aiming",
      "controls": [
        {
          "label": "⟳ Rotate 45°",
          "what": "Turns the piece one step. Eight steps to a full turn."
        },
        {
          "label": "✥ Face",
          "what": "Opens a compass — pick N / NE / E / SE / S / SW / W / NW and it turns to face that way outright."
        },
        {
          "label": "⇋ Mirror",
          "what": "Flips the whole piece left-to-right. Handy for making a matching pair."
        },
        {
          "label": "▲ Scale + / ▼ Scale −",
          "what": "Resizes the piece in ¼ steps."
        },
        {
          "label": "⇡ Raise ½ / ⇣ Lower ½",
          "what": "Floats it up or down half a block at a time (up to 4 up, 6 down)."
        },
        {
          "label": "✥ Nudge ▶",
          "what": "Fine positioning — shifts it a small step in any direction."
        }
      ]
    },
    {
      "title": "Look & finish",
      "controls": [
        {
          "label": "◆ Material ▶",
          "what": "Re-skins the whole piece. Most pieces walk all 355 blocks in the game — the woods (or stones) that piece is naturally made of are listed first, then everything else."
        },
        {
          "label": "◈ Transform ▶",
          "what": "The same thing, but one element at a time — change a table's top without changing its legs."
        },
        {
          "label": "◈ Paper / Cloth",
          "what": "On shoji and screens: Cloth ▸ opaque or Paper ▸ lets light glow."
        },
        {
          "label": "Dressing ▸ shown / hidden",
          "what": "Hides the clutter a piece comes dressed with, leaving the bare furniture."
        },
        {
          "label": "⟲ Reset",
          "what": "Puts every setting back to the maker's original finish."
        }
      ]
    },
    {
      "title": "Shape & motion",
      "controls": [
        {
          "label": "Height ▸ Short / Full",
          "what": "1 block tall or 3 blocks tall."
        },
        {
          "label": "Thin / Wide",
          "what": "Narrow or wide version of the same piece."
        },
        {
          "label": "Length ▸ Short / Long / Floor",
          "what": "How far curtains and hangings fall."
        },
        {
          "label": "⇋ Flip / ⇋ Hinge",
          "what": "Flips just the moving part — which way a door swings, which way a panel slides."
        },
        {
          "label": "⟳ Tilt",
          "what": "Pitches the piece forward/back through 8 stops of 45°."
        },
        {
          "label": "↶ / ↷",
          "what": "Rolls it sideways — a cartwheel, 8 stops of 45°."
        },
        {
          "label": "⛶ Solid / ⛶ Walk Through",
          "what": "Solid bolts it down so you can stand on it and it blocks you. Walk Through makes it decorative again. A bolted piece can't be tilted, and a tilted piece can't be bolted."
        }
      ]
    },
    {
      "title": "Pieces that hold things",
      "controls": [
        {
          "label": "Display slots",
          "what": "Shelves, cases, racks and plinths hold real items — right-click with something in hand to place it, and it draws the actual item."
        },
        {
          "label": "⟳ Rotate / ◍ Spin",
          "what": "Turns a displayed item, or sets it spinning on its plinth."
        },
        {
          "label": "⛓ Reskin",
          "what": "On gear pipes — cycles the metal."
        },
        {
          "label": "▣ Facade",
          "what": "Dresses a pipe in whatever block you're holding."
        },
        {
          "label": "⇅ Vertical",
          "what": "Stands a pipe upright or lays it flat."
        },
        {
          "label": "Tool / Material",
          "what": "On the tool rack — pick Sword, Pickaxe, Axe, Shovel, Hoe and the tier it's made from."
        }
      ]
    },
    {
      "title": "Fire & light",
      "controls": [
        {
          "label": "Emblaze / Snuffed",
          "what": "Lights or puts out fireplaces, braziers, fire pits, candles and lanterns. Lit pieces give off real light."
        },
        {
          "label": "Smoke ▸ On / Off",
          "what": "Whether a lit piece smokes."
        }
      ]
    },
    {
      "title": "Figurines",
      "controls": [
        {
          "label": "Look",
          "what": "Which variant — the cat breeds, the axolotl colours, and so on."
        },
        {
          "label": "Baby ▸ On / Off",
          "what": "Adult or baby."
        },
        {
          "label": "Pose",
          "what": "Standing, Sitting, Sleeping, Crouched, Rolled up."
        },
        {
          "label": "Effect",
          "what": "Adds a particle aura — soul embers and ten others."
        },
        {
          "label": "Stand ▸ Plinth shown / hidden",
          "what": "Show or hide the little base it sits on."
        }
      ]
    },
    {
      "title": "Moving & removing",
      "controls": [
        {
          "label": "⇱ Pick Up",
          "what": "Returns it to your inventory with every setting remembered — material, tilt, scale, the lot. Put it down later and it's exactly as you left it."
        },
        {
          "label": "✥ Move",
          "what": "Aim where you want it and right-click to set it down there."
        },
        {
          "label": "⇄ Replace",
          "what": "Hold a different furnishing, and swap it in where this one stands."
        },
        {
          "label": "✕ Remove",
          "what": "Deletes the piece."
        }
      ]
    }
  ]
} as const
