// GENERATED by tools/legal.py in the forevercraft-datapack repo. Do not edit.
// Every number here is measured from the artefacts that ship; re-run after a
// Furnishings build rather than correcting a figure by hand:
//   python3 tools/legal.py --web <this file> --addon dist/...mcaddon
// Last generated from: Forevercraft-Furnishings-1.0.29.mcaddon

export const LICENSE = {
  "holder": "foreverpal",
  "eula": "https://www.minecraft.net/en-us/eula",
  "furniture": "All The Furniture",
  "allows": [
    "download this pack and use it in your own worlds and on your own servers, for free, for as long as you like",
    "modify your own copy for your own use"
  ],
  "forbids": [
    "sell it",
    "put it behind a paid or ad-gated download",
    "re-upload it elsewhere",
    "redistribute it as part of another pack",
    "present it as your own work"
  ],
  "askFirst": "If you want to build on it or include it in something, ask first.",
  "disclaimer": "NOT AN OFFICIAL MINECRAFT PRODUCT. NOT APPROVED BY OR ASSOCIATED WITH MOJANG OR MICROSOFT. Minecraft is a trademark of Mojang AB.",
  "bedrock": {
    "total": 898,
    "mojang": 649,
    "fromBedrock": 648,
    "fromJava": 1,
    "unmodified": 601,
    "changed": 48,
    "icons": 247,
    "ours": 249
  },
  "packs": [
    {
      "title": "Forevercraft",
      "kind": "Java datapack",
      "vanillaFiles": 241
    },
    {
      "title": "All The Furniture",
      "kind": "Java datapack",
      "vanillaFiles": 144
    },
    {
      "title": "All The Furniture",
      "kind": "Bedrock add-on",
      "vanillaFiles": null
    }
  ]
} as const
